version: '3'

services:
  apache:
    build: ./apache
    ports:
      - "8080"
    volumes:
      - ./html:/var/www/
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    environment:
    - VIRTUAL_HOST=0.0.0.0
    - VIRTUAL_PROTO=http
  node1:
    build: ./nodejs
    ports:
      - "8000"
  node2:
    build: ./nodejs
    ports:
      - "8000"
  node3:
    build: ./nodejs
    ports:
      - "8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
    - VIRTUAL_PORT=8080
