version: '3'

services:
  apache:
    build: ./apache
    ports:
      - "8080"
    volumes:
      - ./html:/var/www/
    environment:
      - VIRTUAL_HOST=0.0.0.0
      - VIRTUAL_PROTO=http
    networks:
      - nginx-apache
      - apache-node
  nodejs:
    build: ./nodejs
    ports:
      - "8000"
    networks:
      - apache-node
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_PORT=8080
    networks:
      - nginx-apache

networks:
  apache-node:
  nginx-apache:
  