version: '3'

services:
  apache:
    build: ./apache
    ports:
      - "8080:8080"
    volumes:
      - ./html:/var/www/
  nodejs:
    build: ./nodejs
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
